<?php
/**
 * FeedbackApi
 * PHP version 7.4
 *
 * @category Class
 * @package  Survos\LibreTranslateBundle
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LibreTranslate
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.11
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Survos\LibreTranslateBundle\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Survos\LibreTranslateBundle\ApiException;
use Survos\LibreTranslateBundle\Configuration;
use Survos\LibreTranslateBundle\HeaderSelector;
use Survos\LibreTranslateBundle\ObjectSerializer;

/**
 * FeedbackApi Class Doc Comment
 *
 * @category Class
 * @package  Survos\LibreTranslateBundle
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FeedbackApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'suggestPost' => [
            'multipart/form-data',
        ],
    ];

/**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation suggestPost
     *
     * Submit a suggestion to improve a translation
     *
     * @param  mixed $q Original text (required)
     * @param  mixed $s Suggested translation (required)
     * @param  mixed $source Language of original text (required)
     * @param  mixed $target Language of suggested translation (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['suggestPost'] to see the possible values for this operation
     *
     * @throws \Survos\LibreTranslateBundle\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Survos\LibreTranslateBundle\Model\SuggestResponse|\Survos\LibreTranslateBundle\Model\ErrorResponse
     */
    public function suggestPost($q, $s, $source, $target, string $contentType = self::contentTypes['suggestPost'][0])
    {
        list($response) = $this->suggestPostWithHttpInfo($q, $s, $source, $target, $contentType);
        return $response;
    }

    /**
     * Operation suggestPostWithHttpInfo
     *
     * Submit a suggestion to improve a translation
     *
     * @param  mixed $q Original text (required)
     * @param  mixed $s Suggested translation (required)
     * @param  mixed $source Language of original text (required)
     * @param  mixed $target Language of suggested translation (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['suggestPost'] to see the possible values for this operation
     *
     * @throws \Survos\LibreTranslateBundle\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Survos\LibreTranslateBundle\Model\SuggestResponse|\Survos\LibreTranslateBundle\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function suggestPostWithHttpInfo($q, $s, $source, $target, string $contentType = self::contentTypes['suggestPost'][0])
    {
        $request = $this->suggestPostRequest($q, $s, $source, $target, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Survos\LibreTranslateBundle\Model\SuggestResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Survos\LibreTranslateBundle\Model\SuggestResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Survos\LibreTranslateBundle\Model\SuggestResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\Survos\LibreTranslateBundle\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Survos\LibreTranslateBundle\Model\ErrorResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Survos\LibreTranslateBundle\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Survos\LibreTranslateBundle\Model\SuggestResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Survos\LibreTranslateBundle\Model\SuggestResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Survos\LibreTranslateBundle\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation suggestPostAsync
     *
     * Submit a suggestion to improve a translation
     *
     * @param  mixed $q Original text (required)
     * @param  mixed $s Suggested translation (required)
     * @param  mixed $source Language of original text (required)
     * @param  mixed $target Language of suggested translation (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['suggestPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function suggestPostAsync($q, $s, $source, $target, string $contentType = self::contentTypes['suggestPost'][0])
    {
        return $this->suggestPostAsyncWithHttpInfo($q, $s, $source, $target, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation suggestPostAsyncWithHttpInfo
     *
     * Submit a suggestion to improve a translation
     *
     * @param  mixed $q Original text (required)
     * @param  mixed $s Suggested translation (required)
     * @param  mixed $source Language of original text (required)
     * @param  mixed $target Language of suggested translation (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['suggestPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function suggestPostAsyncWithHttpInfo($q, $s, $source, $target, string $contentType = self::contentTypes['suggestPost'][0])
    {
        $returnType = '\Survos\LibreTranslateBundle\Model\SuggestResponse';
        $request = $this->suggestPostRequest($q, $s, $source, $target, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'suggestPost'
     *
     * @param  mixed $q Original text (required)
     * @param  mixed $s Suggested translation (required)
     * @param  mixed $source Language of original text (required)
     * @param  mixed $target Language of suggested translation (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['suggestPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function suggestPostRequest($q, $s, $source, $target, string $contentType = self::contentTypes['suggestPost'][0])
    {

        // verify the required parameter 'q' is set
        if ($q === null || (is_array($q) && count($q) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $q when calling suggestPost'
            );
        }

        // verify the required parameter 's' is set
        if ($s === null || (is_array($s) && count($s) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $s when calling suggestPost'
            );
        }

        // verify the required parameter 'source' is set
        if ($source === null || (is_array($source) && count($source) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $source when calling suggestPost'
            );
        }

        // verify the required parameter 'target' is set
        if ($target === null || (is_array($target) && count($target) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $target when calling suggestPost'
            );
        }


        $resourcePath = '/suggest';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;




        // form params
        if ($q !== null) {
            $formParams['q'] = ObjectSerializer::toFormValue($q);
        }
        // form params
        if ($s !== null) {
            $formParams['s'] = ObjectSerializer::toFormValue($s);
        }
        // form params
        if ($source !== null) {
            $formParams['source'] = ObjectSerializer::toFormValue($source);
        }
        // form params
        if ($target !== null) {
            $formParams['target'] = ObjectSerializer::toFormValue($target);
        }

        $headers = $this->headerSelector->selectHeaders(
            ['*/*', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
