services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
###< doctrine/doctrine-bundle ###

###> meilisearch/search-bundle ###
  meilisearch:
    ports:
      - "7700"
###< meilisearch/search-bundle ###
