<?php
/**
 * TranslateApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Survos\LibreTranslateBundle
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LibreTranslate
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.11
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Survos\LibreTranslateBundle\Test\Api;

use \Survos\LibreTranslateBundle\Configuration;
use \Survos\LibreTranslateBundle\ApiException;
use \Survos\LibreTranslateBundle\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TranslateApiTest Class Doc Comment
 *
 * @category Class
 * @package  Survos\LibreTranslateBundle
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TranslateApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for detectPost
     *
     * Detect the language of a single text.
     *
     */
    public function testDetectPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for languagesGet
     *
     * Retrieve list of supported languages.
     *
     */
    public function testLanguagesGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for translateFilePost
     *
     * Translate file from a language to another.
     *
     */
    public function testTranslateFilePost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for translatePost
     *
     * Translate text from a language to another.
     *
     */
    public function testTranslatePost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
