<?php

namespace Container5ICl95i;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKeyValueServiceService extends Survos_KeyValueBundle_Tests_Fixtures_TestKernelTestDebugContainer
{
    /**
     * Gets the private 'Survos\KeyValueBundle\Service\KeyValueService' shared autowired service.
     *
     * @return \Survos\KeyValueBundle\Service\KeyValueService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/src/Service/KeyValueService.php';

        return $container->privates['Survos\\KeyValueBundle\\Service\\KeyValueService'] = new \Survos\KeyValueBundle\Service\KeyValueService(true, [], './', ($container->privates['logger'] ?? self::getLoggerService($container)), ($container->services['debug.stopwatch'] ??= new \Symfony\Component\Stopwatch\Stopwatch(true)), ($container->privates['property_accessor'] ?? $container->load('getPropertyAccessorService')));
    }
}
