<?php

// This file has been auto-generated by the Symfony Dependency Injection Component
// You can reference it in the "opcache.preload" php.ini setting on PHP >= 7.4 when preloading is desired

use Symfony\Component\DependencyInjection\Dumper\Preloader;

if (in_array(PHP_SAPI, ['cli', 'phpdbg', 'embed'], true)) {
    return;
}

require dirname(__DIR__, 4).'/vendor/autoload.php';
(require __DIR__.'/Survos_GeoapifyBundle_Tests_Service_GeoapifyBundleClientTestKernelTestDebugContainer.php')->set(\ContainerOgiAel5\Survos_GeoapifyBundle_Tests_Service_GeoapifyBundleClientTestKernelTestDebugContainer::class, null);
require __DIR__.'/ContainerOgiAel5/getSurvosGeoapifyServiceService.php';

$classes = [];
$classes[] = 'Survos\GeoapifyBundle\SurvosGeoapifyBundle';
$classes[] = 'Symfony\Component\DependencyInjection\ContainerInterface';
$classes[] = 'Survos\GeoapifyBundle\Service\GeoapifyService';

$preloaded = Preloader::preload($classes);
