<?php

namespace Container8o1Cpjb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QHo9PeRService extends Survos_PixieBundle_Tests_Fixtures_TestKernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.qHo9PeR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qHo9PeR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'Survos\\PixieBundle\\Controller\\PixieController::home' => ['privates', '.service_locator.rfCO11c', 'get_ServiceLocator_RfCO11cService', true],
            'Survos\\PixieBundle\\Controller\\PixieController::import' => ['privates', '.service_locator.NWvQ3a1.Survos\\PixieBundle\\Controller\\PixieController::import()', 'getPixieControllerimportService', true],
            'Survos\\PixieBundle\\Controller\\PixieController:home' => ['privates', '.service_locator.rfCO11c', 'get_ServiceLocator_RfCO11cService', true],
            'Survos\\PixieBundle\\Controller\\PixieController:import' => ['privates', '.service_locator.NWvQ3a1.Survos\\PixieBundle\\Controller\\PixieController::import()', 'getPixieControllerimportService', true],
        ], [
            'Survos\\PixieBundle\\Controller\\PixieController::home' => '?',
            'Survos\\PixieBundle\\Controller\\PixieController::import' => '?',
            'Survos\\PixieBundle\\Controller\\PixieController:home' => '?',
            'Survos\\PixieBundle\\Controller\\PixieController:import' => '?',
        ]);
    }
}
