<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXqwT76M\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXqwT76M/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXqwT76M.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXqwT76M\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXqwT76M\App_KernelDevDebugContainer([
    'container.build_hash' => 'XqwT76M',
    'container.build_id' => 'a588d4ba',
    'container.build_time' => 1699893587,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXqwT76M');
