<?php

namespace ContainerONuJ4ef;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TDsuIEService extends Survos_KeyValueBundle_Tests_Fixtures_TestKernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.tDsuIE_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tDsuIE_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'Survos\\KeyValueBundle\\Controller\\PixyController::home' => ['privates', '.service_locator.PkAnQ8f', 'get_ServiceLocator_PkAnQ8fService', true],
            'Survos\\KeyValueBundle\\Controller\\PixyController::import' => ['privates', '.service_locator.7atp9jT.Survos\\KeyValueBundle\\Controller\\PixyController::import()', 'getPixyControllerimportService', true],
            'Survos\\KeyValueBundle\\Controller\\PixyController:home' => ['privates', '.service_locator.PkAnQ8f', 'get_ServiceLocator_PkAnQ8fService', true],
            'Survos\\KeyValueBundle\\Controller\\PixyController:import' => ['privates', '.service_locator.7atp9jT.Survos\\KeyValueBundle\\Controller\\PixyController::import()', 'getPixyControllerimportService', true],
        ], [
            'Survos\\KeyValueBundle\\Controller\\PixyController::home' => '?',
            'Survos\\KeyValueBundle\\Controller\\PixyController::import' => '?',
            'Survos\\KeyValueBundle\\Controller\\PixyController:home' => '?',
            'Survos\\KeyValueBundle\\Controller\\PixyController:import' => '?',
        ]);
    }
}
