<?php

namespace ContainerONuJ4ef;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PkAnQ8fService extends Survos_KeyValueBundle_Tests_Fixtures_TestKernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.PkAnQ8f' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PkAnQ8f'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'chartBuilder' => ['privates', '.errored.RhePoLY', NULL, 'Cannot determine controller argument for "Survos\\KeyValueBundle\\Controller\\PixyController::home()": the $chartBuilder argument is type-hinted with the non-existent class or interface: "Symfony\\UX\\Chartjs\\Builder\\ChartBuilderInterface".'],
        ], [
            'chartBuilder' => '?',
        ]);
    }
}
