<?php

namespace ContainerONuJ4ef;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPixyControllerimportService extends Survos_KeyValueBundle_Tests_Fixtures_TestKernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.7atp9jT.Survos\KeyValueBundle\Controller\PixyController::import()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7atp9jT.Survos\\KeyValueBundle\\Controller\\PixyController::import()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'keyValueService' => ['privates', 'Survos\\KeyValueBundle\\Service\\KeyValueService', 'getKeyValueServiceService', true],
            'pixyImportService' => ['privates', 'Survos\\KeyValueBundle\\Service\\PixyImportService', 'getPixyImportServiceService', true],
        ], [
            'keyValueService' => 'Survos\\KeyValueBundle\\Service\\KeyValueService',
            'pixyImportService' => 'Survos\\KeyValueBundle\\Service\\PixyImportService',
        ]))->withContext('Survos\\KeyValueBundle\\Controller\\PixyController::import()', $container);
    }
}
