<?php
/**
 * FrontendSettingsLanguageSourceTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Survos\LibreTranslateBundle
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LibreTranslate
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.11
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Survos\LibreTranslateBundle\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * FrontendSettingsLanguageSourceTest Class Doc Comment
 *
 * @category    Class
 * @description FrontendSettingsLanguageSource
 * @package     Survos\LibreTranslateBundle
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class FrontendSettingsLanguageSourceTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "FrontendSettingsLanguageSource"
     */
    public function testFrontendSettingsLanguageSource()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "code"
     */
    public function testPropertyCode()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
