<?php

namespace Container9JdZFxX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KHPqzSuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kHPqzSu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kHPqzSu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'official' => ['privates', '.errored..service_locator.kHPqzSu.App\\Entity\\Official', NULL, 'Cannot autowire service ".service_locator.kHPqzSu": it needs an instance of "App\\Entity\\Official" but this type has been excluded in "config/services.yaml".'],
            'officialRepository' => ['privates', 'App\\Repository\\OfficialRepository', 'getOfficialRepositoryService', true],
        ], [
            'official' => 'App\\Entity\\Official',
            'officialRepository' => 'App\\Repository\\OfficialRepository',
        ]);
    }
}
