<?php

namespace Container9JdZFxX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAppLoadDataCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\AppLoadDataCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\AppLoadDataCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:load-data', [], 'Load the congressional data', false, #[\Closure(name: 'App\\Command\\AppLoadDataCommand')] fn (): \App\Command\AppLoadDataCommand => ($container->privates['App\\Command\\AppLoadDataCommand'] ?? $container->load('getAppLoadDataCommandService')));
    }
}
