<?php

namespace Container9JdZFxX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAppImportMuseumsCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\AppImportMuseumsCommand' shared autowired service.
     *
     * @return \App\Command\AppImportMuseumsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/zenstruck/console-extra/src/Invokable.php';
        include_once \dirname(__DIR__, 4).'/vendor/zenstruck/console-extra/src/InvokableServiceCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/zenstruck/console-extra/src/ConfigureWithAttributes.php';
        include_once \dirname(__DIR__, 4).'/vendor/zenstruck/console-extra/src/RunsCommands.php';
        include_once \dirname(__DIR__, 4).'/vendor/zenstruck/console-extra/src/RunsProcesses.php';
        include_once \dirname(__DIR__, 4).'/src/Command/AppImportMuseumsCommand.php';

        $container->privates['App\\Command\\AppImportMuseumsCommand'] = $instance = new \App\Command\AppImportMuseumsCommand();

        $instance->setInvokeContainer((new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'Symfony\\Component\\DependencyInjection\\ParameterBag\\ParameterBagInterface' => ['privates', 'parameter_bag', 'getParameterBagService', false],
            'invoke:importService' => ['privates', 'App\\Service\\ImportService', 'getImportServiceService', true],
        ], [
            'Symfony\\Component\\DependencyInjection\\ParameterBag\\ParameterBagInterface' => '?',
            'invoke:importService' => 'App\\Service\\ImportService',
        ]))->withContext('App\\Command\\AppImportMuseumsCommand', $container));
        $instance->setName('app:import-museums');

        return $instance;
    }
}
