<?php

namespace Container9JdZFxX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getButtonComponentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Survos\BootstrapBundle\Components\ButtonComponent' autowired service.
     *
     * @return \Survos\BootstrapBundle\Components\ButtonComponent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/survos/bootstrap-bundle/src/Components/ButtonComponent.php';

        $container->factories['service_container']['Survos\\BootstrapBundle\\Components\\ButtonComponent'] = function ($container) {
            return new \Survos\BootstrapBundle\Components\ButtonComponent();
        };

        return $container->factories['service_container']['Survos\\BootstrapBundle\\Components\\ButtonComponent']($container);
    }
}
