<?php

namespace Container9JdZFxX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDropdownComponentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Survos\BootstrapBundle\Components\DropdownComponent' autowired service.
     *
     * @return \Survos\BootstrapBundle\Components\DropdownComponent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/survos/bootstrap-bundle/src/Components/DropdownComponent.php';

        $container->factories['service_container']['Survos\\BootstrapBundle\\Components\\DropdownComponent'] = function ($container) {
            return new \Survos\BootstrapBundle\Components\DropdownComponent();
        };

        return $container->factories['service_container']['Survos\\BootstrapBundle\\Components\\DropdownComponent']($container);
    }
}
