<?php

namespace Container9JdZFxX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMenuComponentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Survos\BootstrapBundle\Components\MenuComponent' autowired service.
     *
     * @return \Survos\BootstrapBundle\Components\MenuComponent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/survos/bootstrap-bundle/src/Components/MenuComponent.php';

        $container->factories['service_container']['Survos\\BootstrapBundle\\Components\\MenuComponent'] = function ($container) {
            $a = ($container->privates['knp_menu.helper'] ?? self::getKnpMenu_HelperService($container));

            if (isset($container->privates['Survos\\BootstrapBundle\\Components\\MenuComponent'])) {
                return $container->privates['Survos\\BootstrapBundle\\Components\\MenuComponent'];
            }
            $b = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

            if (isset($container->privates['Survos\\BootstrapBundle\\Components\\MenuComponent'])) {
                return $container->privates['Survos\\BootstrapBundle\\Components\\MenuComponent'];
            }

            return new \Survos\BootstrapBundle\Components\MenuComponent(['showAppMenu' => false], $a, ($container->services['knp_menu.factory'] ?? $container->load('getKnpMenu_FactoryService')), $b);
        };

        return $container->factories['service_container']['Survos\\BootstrapBundle\\Components\\MenuComponent']($container);
    }
}
