<?php

namespace Container9JdZFxX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStimulus_UxControllersTwigRuntimeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'stimulus.ux_controllers_twig_runtime' shared service.
     *
     * @return \Symfony\UX\StimulusBundle\Twig\UxControllersTwigRuntime
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/twig/twig/src/Extension/RuntimeExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/stimulus-bundle/src/Twig/UxControllersTwigRuntime.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/stimulus-bundle/src/AssetMapper/ControllersMapGenerator.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/stimulus-bundle/src/Ux/UxPackageReader.php';

        $a = ($container->privates['asset_mapper'] ?? self::getAssetMapperService($container));
        $b = new \Symfony\UX\StimulusBundle\Ux\UxPackageReader(\dirname(__DIR__, 4));

        return $container->privates['stimulus.ux_controllers_twig_runtime'] = new \Symfony\UX\StimulusBundle\Twig\UxControllersTwigRuntime(new \Symfony\UX\StimulusBundle\AssetMapper\ControllersMapGenerator($a, $b, [(\dirname(__DIR__, 4).'/assets/controllers')], (\dirname(__DIR__, 4).'/assets/controllers.json')), $a, $b, \dirname(__DIR__, 4));
    }
}
