<?php

namespace Container57M1xJi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Oqt1cOIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Oqt1cOI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Oqt1cOI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'termRepository' => ['privates', 'App\\Repository\\TermRepository', 'getTermRepositoryService', true],
        ], [
            'termRepository' => 'App\\Repository\\TermRepository',
        ]);
    }
}
