<?php

namespace Container57M1xJi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAccordionComponentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Survos\BootstrapBundle\Components\AccordionComponent' autowired service.
     *
     * @return \Survos\BootstrapBundle\Components\AccordionComponent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/survos/bootstrap-bundle/src/Components/AccordionComponent.php';

        $container->factories['service_container']['Survos\\BootstrapBundle\\Components\\AccordionComponent'] = function ($container) {
            return new \Survos\BootstrapBundle\Components\AccordionComponent();
        };

        return $container->factories['service_container']['Survos\\BootstrapBundle\\Components\\AccordionComponent']($container);
    }
}
