<?php

namespace Container57M1xJi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAppMenuMenuEventListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventListener\AppMenuMenuEventListener' shared autowired service.
     *
     * @return \App\EventListener\AppMenuMenuEventListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/survos/bootstrap-bundle/src/Traits/KnpMenuHelperInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/survos/bootstrap-bundle/src/Traits/KnpMenuHelperTrait.php';
        include_once \dirname(__DIR__, 4).'/src/EventListener/AppMenuMenuEventListener.php';

        $a = ($container->privates['security.authorization_checker'] ?? self::getSecurity_AuthorizationCheckerService($container));

        if (isset($container->privates['App\\EventListener\\AppMenuMenuEventListener'])) {
            return $container->privates['App\\EventListener\\AppMenuMenuEventListener'];
        }

        return $container->privates['App\\EventListener\\AppMenuMenuEventListener'] = new \App\EventListener\AppMenuMenuEventListener($a);
    }
}
