<?php

namespace Container57M1xJi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnnotatedAppEntityOfficialApiPlatformDoctrineOrmFilterOrderFilterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'annotated_app_entity_official_api_platform_doctrine_orm_filter_order_filter' shared autowired service.
     *
     * @return \ApiPlatform\Doctrine\Orm\Filter\OrderFilter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/Api/FilterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/Doctrine/Orm/Filter/FilterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/Doctrine/Orm/PropertyHelperTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/Doctrine/Common/PropertyHelperTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/Doctrine/Orm/Filter/AbstractFilter.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/Doctrine/Common/Filter/OrderFilterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/Doctrine/Common/Filter/OrderFilterTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/Doctrine/Orm/Filter/OrderFilter.php';

        return $container->privates['annotated_app_entity_official_api_platform_doctrine_orm_filter_order_filter'] = new \ApiPlatform\Doctrine\Orm\Filter\OrderFilter(($container->services['doctrine'] ?? self::getDoctrineService($container)), 'order', ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), ['id' => NULL, 'firstName' => NULL, 'lastName' => NULL, 'birthday' => NULL], ($container->privates['serializer.name_converter.metadata_aware'] ?? self::getSerializer_NameConverter_MetadataAwareService($container)), NULL);
    }
}
