<?php

namespace Container57M1xJi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBadgeComponentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Survos\BootstrapBundle\Components\BadgeComponent' autowired service.
     *
     * @return \Survos\BootstrapBundle\Components\BadgeComponent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/survos/bootstrap-bundle/src/Components/BadgeComponent.php';

        $container->factories['service_container']['Survos\\BootstrapBundle\\Components\\BadgeComponent'] = function ($container) {
            return new \Survos\BootstrapBundle\Components\BadgeComponent();
        };

        return $container->factories['service_container']['Survos\\BootstrapBundle\\Components\\BadgeComponent']($container);
    }
}
