<?php

namespace Container57M1xJi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getItemGridComponentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Survos\Grid\Components\ItemGridComponent' autowired service.
     *
     * @return \Survos\Grid\Components\ItemGridComponent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/survos/grid-bundle/src/Components/ItemGridComponent.php';

        $container->factories['service_container']['Survos\\Grid\\Components\\ItemGridComponent'] = function ($container) {
            return new \Survos\Grid\Components\ItemGridComponent();
        };

        return $container->factories['service_container']['Survos\\Grid\\Components\\ItemGridComponent']($container);
    }
}
