<?php

namespace Container57M1xJi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLastModifiedProcessorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Stenope\Bundle\Processor\LastModifiedProcessor' shared service.
     *
     * @return \Stenope\Bundle\Processor\LastModifiedProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/stenope/stenope/src/Behaviour/ProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/stenope/stenope/src/Processor/LastModifiedProcessor.php';
        include_once \dirname(__DIR__, 4).'/vendor/stenope/stenope/src/Service/Git/LastModifiedFetcher.php';

        return $container->privates['Stenope\\Bundle\\Processor\\LastModifiedProcessor'] = new \Stenope\Bundle\Processor\LastModifiedProcessor('lastModified', new \Stenope\Bundle\Service\Git\LastModifiedFetcher('git', ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container))));
    }
}
