<?php

namespace Container57M1xJi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMeiliSearchStateProviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Survos\ApiGrid\State\MeiliSearchStateProvider' shared autowired service.
     *
     * @return \Survos\ApiGrid\State\MeiliSearchStateProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/survos/api-grid-bundle/src/State/MeiliSearchStateProvider.php';

        $a = ($container->privates['debug.serializer'] ?? self::getDebug_SerializerService($container));

        if (isset($container->services['Survos\\ApiGrid\\State\\MeiliSearchStateProvider'])) {
            return $container->services['Survos\\ApiGrid\\State\\MeiliSearchStateProvider'];
        }
        $b = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->services['Survos\\ApiGrid\\State\\MeiliSearchStateProvider'])) {
            return $container->services['Survos\\ApiGrid\\State\\MeiliSearchStateProvider'];
        }

        return $container->services['Survos\\ApiGrid\\State\\MeiliSearchStateProvider'] = new \Survos\ApiGrid\State\MeiliSearchStateProvider($a, $b, ($container->privates['api_platform.pagination'] ?? $container->load('getApiPlatform_PaginationService')), new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'Survos\\ApiGrid\\Filter\\MeiliSearch\\DataTableFacetsFilter' => ['privates', 'Survos\\ApiGrid\\Filter\\MeiliSearch\\DataTableFacetsFilter', 'getDataTableFacetsFilterService', true],
            'Survos\\ApiGrid\\Filter\\MeiliSearch\\DataTableFilter' => ['privates', 'Survos\\ApiGrid\\Filter\\MeiliSearch\\DataTableFilter', 'getDataTableFilterService', true],
            'Survos\\ApiGrid\\Filter\\MeiliSearch\\MultiFieldSearchFilter' => ['privates', 'Survos\\ApiGrid\\Filter\\MeiliSearch\\MultiFieldSearchFilter', 'getMultiFieldSearchFilter2Service', true],
            'Survos\\ApiGrid\\Filter\\MeiliSearch\\SortFilter' => ['privates', 'Survos\\ApiGrid\\Filter\\MeiliSearch\\SortFilter', 'getSortFilterService', true],
        ], [
            'Survos\\ApiGrid\\Filter\\MeiliSearch\\DataTableFacetsFilter' => 'Survos\\ApiGrid\\Filter\\MeiliSearch\\DataTableFacetsFilter',
            'Survos\\ApiGrid\\Filter\\MeiliSearch\\DataTableFilter' => 'Survos\\ApiGrid\\Filter\\MeiliSearch\\DataTableFilter',
            'Survos\\ApiGrid\\Filter\\MeiliSearch\\MultiFieldSearchFilter' => 'Survos\\ApiGrid\\Filter\\MeiliSearch\\MultiFieldSearchFilter',
            'Survos\\ApiGrid\\Filter\\MeiliSearch\\SortFilter' => 'Survos\\ApiGrid\\Filter\\MeiliSearch\\SortFilter',
        ]), 'http://127.0.0.1:7700', 'masterKey', $a);
    }
}
