<?php

namespace Container57M1xJi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOAuthControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Survos\AuthBundle\Controller\OAuthController' shared autowired service.
     *
     * @return \Survos\AuthBundle\Controller\OAuthController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/survos/auth-bundle/src/Controller/OAuthController.php';
        include_once \dirname(__DIR__, 4).'/vendor/knpuniversity/oauth2-client-bundle/src/Client/ClientRegistry.php';

        $container->services['Survos\\AuthBundle\\Controller\\OAuthController'] = $instance = new \Survos\AuthBundle\Controller\OAuthController(($container->services['survos_auth.base_service'] ?? $container->load('getSurvosAuth_BaseServiceService')), ($container->services['doctrine'] ?? self::getDoctrineService($container)), ($container->services['router'] ?? self::getRouterService($container)), ($container->services['knpu.oauth2.registry'] ??= new \KnpU\OAuth2ClientBundle\Client\ClientRegistry($container, [])), ($container->privates['security.user.provider.concrete.app_user_provider'] ?? $container->load('getSecurity_User_Provider_Concrete_AppUserProviderService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), 'App\\Entity\\User');

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('Survos\\AuthBundle\\Controller\\OAuthController', $container));

        return $instance;
    }
}
