<?php

namespace Container57M1xJi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSimpleDatatablesComponentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Survos\SimpleDatatables\Components\SimpleDatatablesComponent' autowired service.
     *
     * @return \Survos\SimpleDatatables\Components\SimpleDatatablesComponent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/survos/simple-datatables-bundle/src/Components/SimpleDatatablesComponent.php';

        $container->factories['service_container']['Survos\\SimpleDatatables\\Components\\SimpleDatatablesComponent'] = function ($container) {
            $a = ($container->privates['twig'] ?? self::getTwigService($container));

            if (isset($container->privates['Survos\\SimpleDatatables\\Components\\SimpleDatatablesComponent'])) {
                return $container->privates['Survos\\SimpleDatatables\\Components\\SimpleDatatablesComponent'];
            }

            return new \Survos\SimpleDatatables\Components\SimpleDatatablesComponent($a, ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), '@survos/simple-datatables-bundle/table');
        };

        return $container->factories['service_container']['Survos\\SimpleDatatables\\Components\\SimpleDatatablesComponent']($container);
    }
}
