<?php

namespace Container57M1xJi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSurvosAuth_BaseServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'survos_auth.base_service' shared autowired service.
     *
     * @return \Survos\AuthBundle\Services\AuthService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/survos/auth-bundle/src/Services/AuthService.php';
        include_once \dirname(__DIR__, 4).'/vendor/knpuniversity/oauth2-client-bundle/src/Client/ClientRegistry.php';

        return $container->services['survos_auth.base_service'] = new \Survos\AuthBundle\Services\AuthService('App\\Entity\\User', ['user_provider' => NULL, 'user_class' => 'App\\Entity\\User'], ($container->services['knpu.oauth2.registry'] ??= new \KnpU\OAuth2ClientBundle\Client\ClientRegistry($container, [])));
    }
}
