<?php

namespace Container57M1xJi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserCreateCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Survos\AuthBundle\Command\UserCreateCommand' shared autowired service.
     *
     * @return \Survos\AuthBundle\Command\UserCreateCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/survos/auth-bundle/src/Command/UserCreateCommand.php';

        $container->privates['Survos\\AuthBundle\\Command\\UserCreateCommand'] = $instance = new \Survos\AuthBundle\Command\UserCreateCommand(($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')), ($container->privates['security.user.provider.concrete.app_user_provider'] ?? $container->load('getSecurity_User_Provider_Concrete_AppUserProviderService')), ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container)), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('survos:user:create');
        $instance->setDescription('create a new user with a password');

        return $instance;
    }
}
