<?php

namespace Container57M1xJi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUx_TwigComponent_Command_DebugService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'ux.twig_component.command.debug' shared service.
     *
     * @return \Symfony\UX\TwigComponent\Command\TwigComponentDebugCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-twig-component/src/Command/TwigComponentDebugCommand.php';

        $container->privates['ux.twig_component.command.debug'] = $instance = new \Symfony\UX\TwigComponent\Command\TwigComponentDebugCommand((\dirname(__DIR__, 4).'/templates'), ($container->privates['ux.twig_component.component_factory'] ?? self::getUx_TwigComponent_ComponentFactoryService($container)), ($container->privates['twig'] ?? self::getTwigService($container)), ['Survos\\Datatables\\Components\\GridComponent' => 'grid', 'Survos\\Datatables\\Components\\ItemGridComponent' => 'item_grid', 'Survos\\BootstrapBundle\\Components\\AlertComponent' => 'alert', 'Survos\\BootstrapBundle\\Components\\AccordionComponent' => 'accordion', 'Survos\\BootstrapBundle\\Components\\BrandComponent' => 'brand', 'Survos\\BootstrapBundle\\Components\\BadgeComponent' => 'badge', 'Survos\\BootstrapBundle\\Components\\ButtonComponent' => 'button', 'Survos\\BootstrapBundle\\Components\\CardComponent' => 'card', 'Survos\\BootstrapBundle\\Components\\CarouselComponent' => 'carousel', 'Survos\\BootstrapBundle\\Components\\DropdownComponent' => 'bs:dropdown', 'Survos\\BootstrapBundle\\Components\\DividerComponent' => 'divider', 'Survos\\BootstrapBundle\\Components\\LinkComponent' => 'link', 'Survos\\BootstrapBundle\\Twig\\Components\\MiniCard' => 'tabler:mini-card', 'Survos\\BootstrapBundle\\Twig\\Components\\TablerIcon' => 'tabler:icon', 'Survos\\BootstrapBundle\\Twig\\Components\\TablerHead' => 'tabler:head', 'Survos\\BootstrapBundle\\Twig\\Components\\TablerPageHeader' => 'tabler:page-header', 'Survos\\BootstrapBundle\\Components\\MenuComponent' => 'menu', 'Survos\\BootstrapBundle\\Components\\MenuBreadcrumbComponent' => 'menu_breadcrumb', 'Survos\\ApiGrid\\Components\\ApiGridComponent' => 'api_grid', 'Survos\\SimpleDatatables\\Components\\SimpleDatatablesComponent' => 'simple_datatables', 'Survos\\SimpleDatatables\\Components\\ItemGridComponent' => 'item_grid', 'Survos\\Grid\\Components\\GridComponent' => 'grid', 'Survos\\Grid\\Components\\ItemGridComponent' => 'item_grid'], NULL);

        $instance->setName('debug:twig-component');
        $instance->setDescription('Display components and them usages for an application');

        return $instance;
    }
}
