survos_bunny:
  api_key: '%env(BUNNY_API_KEY)%'
  storage_zone: '%env(BUNNY_STORAGE_ZONE)%'
  region: '%env(BUNNY_REGION)%'
  password: '%env(BUNNY_PASSWORD)%'
  readonly_password: '%env(BUNNY_READONLY_PASSWORD)%'
