<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8o1Cpjb\Survos_PixieBundle_Tests_Fixtures_TestKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8o1Cpjb/Survos_PixieBundle_Tests_Fixtures_TestKernelTestDebugContainer.php') {
    touch(__DIR__.'/Container8o1Cpjb.legacy');

    return;
}

if (!\class_exists(Survos_PixieBundle_Tests_Fixtures_TestKernelTestDebugContainer::class, false)) {
    \class_alias(\Container8o1Cpjb\Survos_PixieBundle_Tests_Fixtures_TestKernelTestDebugContainer::class, Survos_PixieBundle_Tests_Fixtures_TestKernelTestDebugContainer::class, false);
}

return new \Container8o1Cpjb\Survos_PixieBundle_Tests_Fixtures_TestKernelTestDebugContainer([
    'container.build_hash' => '8o1Cpjb',
    'container.build_id' => '4f06c257',
    'container.build_time' => 1719782794,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container8o1Cpjb');
