<?php
/**
 * DetectionsInner
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * LibreTranslate
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.11
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the DetectionsInner model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */

class DetectionsInner 
{
        /**
     * Confidence value
     *
     * @var float|null
     * @SerializedName("confidence")
     * @Assert\Type("float")
     * @Type("float")
     * @Assert\GreaterThanOrEqual(0)
     * @Assert\LessThanOrEqual(1)
     */
    protected ?float $confidence = null;

    /**
     * Language code
     *
     * @var string|null
     * @SerializedName("language")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $language = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->confidence = $data['confidence'] ?? null;
        $this->language = $data['language'] ?? null;
    }

    /**
     * Gets confidence.
     *
     * @return float|null
     */
    public function getConfidence(): ?float
    {
        return $this->confidence;
    }

    /**
     * Sets confidence.
     *
     * @param float|null $confidence  Confidence value
     *
     * @return $this
     */
    public function setConfidence(?float $confidence = null): self
    {
        $this->confidence = $confidence;

        return $this;
    }

    /**
     * Gets language.
     *
     * @return string|null
     */
    public function getLanguage(): ?string
    {
        return $this->language;
    }

    /**
     * Sets language.
     *
     * @param string|null $language  Language code
     *
     * @return $this
     */
    public function setLanguage(?string $language = null): self
    {
        $this->language = $language;

        return $this;
    }
}


