<?php
/**
 * FrontendSettingsLanguage
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * LibreTranslate
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.11
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the FrontendSettingsLanguage model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */

class FrontendSettingsLanguage 
{
        /**
     * @var FrontendSettingsLanguageSource|null
     * @SerializedName("source")
     * @Assert\Type("OpenAPI\Server\Model\FrontendSettingsLanguageSource")
     * @Type("OpenAPI\Server\Model\FrontendSettingsLanguageSource")
     */
    protected ?FrontendSettingsLanguageSource $source = null;

    /**
     * @var FrontendSettingsLanguageSource|null
     * @SerializedName("target")
     * @Assert\Type("OpenAPI\Server\Model\FrontendSettingsLanguageSource")
     * @Type("OpenAPI\Server\Model\FrontendSettingsLanguageSource")
     */
    protected ?FrontendSettingsLanguageSource $target = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->source = $data['source'] ?? null;
        $this->target = $data['target'] ?? null;
    }

    /**
     * Gets source.
     *
     * @return FrontendSettingsLanguageSource|null
     */
    public function getSource(): ?FrontendSettingsLanguageSource
    {
        return $this->source;
    }

    /**
     * Sets source.
     *
     * @param FrontendSettingsLanguageSource|null $source
     *
     * @return $this
     */
    public function setSource(?FrontendSettingsLanguageSource $source = null): self
    {
        $this->source = $source;

        return $this;
    }

    /**
     * Gets target.
     *
     * @return FrontendSettingsLanguageSource|null
     */
    public function getTarget(): ?FrontendSettingsLanguageSource
    {
        return $this->target;
    }

    /**
     * Sets target.
     *
     * @param FrontendSettingsLanguageSource|null $target
     *
     * @return $this
     */
    public function setTarget(?FrontendSettingsLanguageSource $target = null): self
    {
        $this->target = $target;

        return $this;
    }
}


