<?php
/**
 * Translate
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * LibreTranslate
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.11
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the Translate model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */

class Translate 
{
        /**
     * Translated text(s)
     *
     * @var array|null
     * @SerializedName("translatedText")
     * @Assert\Type("array")
     * @Type("array")
     */
    protected ?array $translatedText = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->translatedText = $data['translatedText'] ?? null;
    }

    /**
     * Gets translatedText.
     *
     * @return array|null
     */
    public function getTranslatedText(): ?array
    {
        return $this->translatedText;
    }

    /**
     * Sets translatedText.
     *
     * @param array|null $translatedText  Translated text(s)
     *
     * @return $this
     */
    public function setTranslatedText(?array $translatedText = null): self
    {
        $this->translatedText = $translatedText;

        return $this;
    }
}


