<?php
/**
 * TranslateFile
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * LibreTranslate
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.11
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the TranslateFile model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */

class TranslateFile 
{
        /**
     * Translated file url
     *
     * @var string|null
     * @SerializedName("translatedFileUrl")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $translatedFileUrl = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->translatedFileUrl = $data['translatedFileUrl'] ?? null;
    }

    /**
     * Gets translatedFileUrl.
     *
     * @return string|null
     */
    public function getTranslatedFileUrl(): ?string
    {
        return $this->translatedFileUrl;
    }

    /**
     * Sets translatedFileUrl.
     *
     * @param string|null $translatedFileUrl  Translated file url
     *
     * @return $this
     */
    public function setTranslatedFileUrl(?string $translatedFileUrl = null): self
    {
        $this->translatedFileUrl = $translatedFileUrl;

        return $this;
    }
}


