<?php

namespace ContainerOgiAel5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSurvosGeoapifyServiceService extends Survos_GeoapifyBundle_Tests_Service_GeoapifyBundleClientTestKernelTestDebugContainer
{
    /**
     * Gets the public 'survos_geoapify_service' shared autowired service.
     *
     * @return \Survos\GeoapifyBundle\Service\GeoapifyService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/src/Service/GeoapifyService.php';

        return $container->services['survos_geoapify_service'] = new \Survos\GeoapifyBundle\Service\GeoapifyService($container->getEnv('GEOAPIFY_API_KEY'));
    }
}
