<?php

namespace ContainerSKmAIvw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAlertComponentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Survos\BootstrapBundle\Components\AlertComponent' autowired service.
     *
     * @return \Survos\BootstrapBundle\Components\AlertComponent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/packages/bootstrap-bundle/src/Components/AlertComponent.php';

        $container->factories['service_container']['Survos\\BootstrapBundle\\Components\\AlertComponent'] = function ($container) {
            return new \Survos\BootstrapBundle\Components\AlertComponent();
        };

        return $container->factories['service_container']['Survos\\BootstrapBundle\\Components\\AlertComponent']($container);
    }
}
