<?php

namespace ContainerSKmAIvw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCrawlCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.Survos\CrawlerBundle\Command\CrawlCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.Survos\\CrawlerBundle\\Command\\CrawlCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('survos:crawl', [], 'Crawl a website with different users', false, #[\Closure(name: 'Survos\\CrawlerBundle\\Command\\CrawlCommand')] fn (): \Survos\CrawlerBundle\Command\CrawlCommand => ($container->privates['Survos\\CrawlerBundle\\Command\\CrawlCommand'] ?? $container->load('getCrawlCommandService')));
    }
}
