<?php

namespace ContainerSKmAIvw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCrawlerControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Survos\CrawlerBundle\Controller\CrawlerController' shared autowired service.
     *
     * @return \Survos\CrawlerBundle\Controller\CrawlerController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/survos/crawler-bundle/src/Controller/CrawlerController.php';

        $container->services['Survos\\CrawlerBundle\\Controller\\CrawlerController'] = $instance = new \Survos\CrawlerBundle\Controller\CrawlerController(($container->privates['parameter_bag'] ??= new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container)));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('Survos\\CrawlerBundle\\Controller\\CrawlerController', $container));

        return $instance;
    }
}
