<?php

namespace ContainerSKmAIvw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImportServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\ImportService' shared autowired service.
     *
     * @return \App\Service\ImportService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/ImportService.php';

        return $container->privates['App\\Service\\ImportService'] = new \App\Service\ImportService(($container->privates['parameter_bag'] ??= new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container)));
    }
}
