<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5ICl95i\Survos_KeyValueBundle_Tests_Fixtures_TestKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5ICl95i/Survos_KeyValueBundle_Tests_Fixtures_TestKernelTestDebugContainer.php') {
    touch(__DIR__.'/Container5ICl95i.legacy');

    return;
}

if (!\class_exists(Survos_KeyValueBundle_Tests_Fixtures_TestKernelTestDebugContainer::class, false)) {
    \class_alias(\Container5ICl95i\Survos_KeyValueBundle_Tests_Fixtures_TestKernelTestDebugContainer::class, Survos_KeyValueBundle_Tests_Fixtures_TestKernelTestDebugContainer::class, false);
}

return new \Container5ICl95i\Survos_KeyValueBundle_Tests_Fixtures_TestKernelTestDebugContainer([
    'container.build_hash' => '5ICl95i',
    'container.build_id' => '13acdbc4',
    'container.build_time' => 1719741504,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container5ICl95i');
