<?php

/**
 * FeedbackController
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Controller
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * LibreTranslate
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.11
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Controller;

use \Exception;
use JMS\Serializer\Exception\RuntimeException as SerializerRuntimeException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\HttpException;
use Symfony\Component\Validator\Constraints as Assert;
use OpenAPI\Server\Api\FeedbackApiInterface;
use OpenAPI\Server\Model\ErrorResponse;
use OpenAPI\Server\Model\SuggestResponse;

/**
 * FeedbackController Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Server\Controller
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */
class FeedbackController extends Controller
{

    /**
     * Operation suggestPost
     *
     * Submit a suggestion to improve a translation
     *
     * @param Request $request The Symfony request to handle.
     * @return Response The Symfony response.
     */
    public function suggestPostAction(Request $request)
    {
        // Figure out what data format to return to the client
        $produces = ['*/*'];
        // Figure out what the client accepts
        $clientAccepts = $request->headers->has('Accept')?$request->headers->get('Accept'):'*/*';
        $responseFormat = $this->getOutputFormat($clientAccepts, $produces);
        if ($responseFormat === null) {
            return new Response('', 406);
        }

        // Handle authentication

        // Read out all input parameter values into variables
        $q = $request->request->get('q');
        $s = $request->request->get('s');
        $source = $request->request->get('source');
        $target = $request->request->get('target');

        // Use the default value if no value was provided

        // Deserialize the input values that needs it
        try {
            $q = $this->deserialize($q, 'AnyType', 'string');
            $s = $this->deserialize($s, 'AnyType', 'string');
            $source = $this->deserialize($source, 'AnyType', 'string');
            $target = $this->deserialize($target, 'AnyType', 'string');
        } catch (SerializerRuntimeException $exception) {
            return $this->createBadRequestResponse($exception->getMessage());
        }

        // Validate the input values
        $asserts = [];
        $asserts[] = new Assert\NotNull();
        $asserts[] = new Assert\Type("AnyType");
        $asserts[] = new Assert\Valid();
        $response = $this->validate($q, $asserts);
        if ($response instanceof Response) {
            return $response;
        }
        $asserts = [];
        $asserts[] = new Assert\NotNull();
        $asserts[] = new Assert\Type("AnyType");
        $asserts[] = new Assert\Valid();
        $response = $this->validate($s, $asserts);
        if ($response instanceof Response) {
            return $response;
        }
        $asserts = [];
        $asserts[] = new Assert\NotNull();
        $asserts[] = new Assert\Type("AnyType");
        $asserts[] = new Assert\Valid();
        $response = $this->validate($source, $asserts);
        if ($response instanceof Response) {
            return $response;
        }
        $asserts = [];
        $asserts[] = new Assert\NotNull();
        $asserts[] = new Assert\Type("AnyType");
        $asserts[] = new Assert\Valid();
        $response = $this->validate($target, $asserts);
        if ($response instanceof Response) {
            return $response;
        }


        try {
            $handler = $this->getApiHandler();


            // Make the call to the business logic
            $responseCode = 200;
            $responseHeaders = [];

            $result = $handler->suggestPost($q, $s, $source, $target, $responseCode, $responseHeaders);

            // Find default response message
            $message = '';

            // Find a more specific message, if available
            switch ($responseCode) {
                case 200:
                    $message = 'Success';
                    break;
                case 403:
                    $message = 'Not authorized';
                    break;
            }

            return new Response(
                $result !== null ?$this->serialize($result, $responseFormat):'',
                $responseCode,
                array_merge(
                    $responseHeaders,
                    [
                        'Content-Type' => $responseFormat,
                        'X-OpenAPI-Message' => $message
                    ]
                )
            );
        } catch (\Throwable $fallthrough) {
            return $this->createErrorResponse(new HttpException(500, 'An unsuspected error occurred.', $fallthrough));
        }
    }

    /**
     * Returns the handler for this API controller.
     * @return FeedbackApiInterface
     */
    public function getApiHandler()
    {
        return $this->apiServer->getApiHandler('feedback');
    }
}
