<?php

namespace ContainerXqwT76M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0XuEpc8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0XuEpc8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0XuEpc8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'term' => ['privates', '.errored..service_locator.0XuEpc8.App\\Entity\\Term', NULL, 'Cannot autowire service ".service_locator.0XuEpc8": it needs an instance of "App\\Entity\\Term" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'term' => 'App\\Entity\\Term',
        ]);
    }
}
