<?php

namespace ContainerXqwT76M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IZvv3xService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IZvv_3x' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IZvv_3x'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'term' => ['privates', '.errored..service_locator.IZvv_3x.App\\Entity\\Term', NULL, 'Cannot autowire service ".service_locator.IZvv_3x": it needs an instance of "App\\Entity\\Term" but this type has been excluded in "config/services.yaml".'],
        ], [
            'term' => 'App\\Entity\\Term',
        ]);
    }
}
