<?php

namespace ContainerXqwT76M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBrandComponentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Survos\BootstrapBundle\Components\BrandComponent' autowired service.
     *
     * @return \Survos\BootstrapBundle\Components\BrandComponent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/survos/bootstrap-bundle/src/Components/BrandComponent.php';

        $container->factories['service_container']['Survos\\BootstrapBundle\\Components\\BrandComponent'] = function ($container) {
            return new \Survos\BootstrapBundle\Components\BrandComponent();
        };

        return $container->factories['service_container']['Survos\\BootstrapBundle\\Components\\BrandComponent']($container);
    }
}
