<?php

namespace ContainerXqwT76M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContentRuntimeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Stenope\Bundle\Twig\ContentRuntime' shared service.
     *
     * @return \Stenope\Bundle\Twig\ContentRuntime
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/twig/twig/src/Extension/RuntimeExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/stenope/stenope/src/Twig/ContentRuntime.php';

        return $container->privates['Stenope\\Bundle\\Twig\\ContentRuntime'] = new \Stenope\Bundle\Twig\ContentRuntime(($container->privates['Stenope\\Bundle\\ContentManager'] ?? $container->load('getContentManagerService')));
    }
}
