<?php

namespace ContainerXqwT76M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDebugCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Stenope\Bundle\Command\DebugCommand' shared service.
     *
     * @return \Stenope\Bundle\Command\DebugCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/stenope/stenope/src/Command/StopwatchHelperTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/stenope/stenope/src/Command/DebugCommand.php';

        $container->privates['Stenope\\Bundle\\Command\\DebugCommand'] = $instance = new \Stenope\Bundle\Command\DebugCommand(($container->privates['Stenope\\Bundle\\ContentManager'] ?? $container->load('getContentManagerService')), ($container->privates['stenope.build.stopwatch'] ??= new \Symfony\Component\Stopwatch\Stopwatch(true)), []);

        $instance->setName('debug:stenope:content');

        return $instance;
    }
}
