<?php

namespace ContainerXqwT76M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHtmlIdProcessorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Stenope\Bundle\Processor\HtmlIdProcessor' shared service.
     *
     * @return \Stenope\Bundle\Processor\HtmlIdProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/stenope/stenope/src/Behaviour/ProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/stenope/stenope/src/Processor/HtmlIdProcessor.php';
        include_once \dirname(__DIR__, 4).'/vendor/stenope/stenope/src/Behaviour/HtmlCrawlerManagerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/stenope/stenope/src/Service/NaiveHtmlCrawlerManager.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/string/Slugger/SluggerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/string/Slugger/AsciiSlugger.php';

        return $container->privates['Stenope\\Bundle\\Processor\\HtmlIdProcessor'] = new \Stenope\Bundle\Processor\HtmlIdProcessor(($container->privates['Stenope\\Bundle\\Service\\NaiveHtmlCrawlerManager'] ??= new \Stenope\Bundle\Service\NaiveHtmlCrawlerManager()), 'content', ($container->privates['slugger'] ??= new \Symfony\Component\String\Slugger\AsciiSlugger('en')));
    }
}
