<?php

namespace ContainerXqwT76M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOfficial2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.bXpJFPH.App\Entity\Official' shared service.
     *
     * @return \App\Entity\Official
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.bXpJFPH": it needs an instance of "App\\Entity\\Official" but this type has been excluded in "config/services.yaml".');
    }
}
