<?php

namespace ContainerXqwT76M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrismService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Stenope\Bundle\Highlighter\Prism' shared service.
     *
     * @return \Stenope\Bundle\Highlighter\Prism
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/stenope/stenope/src/Behaviour/HighlighterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/stenope/stenope/src/Highlighter/Prism.php';

        return $container->privates['Stenope\\Bundle\\Highlighter\\Prism'] = new \Stenope\Bundle\Highlighter\Prism(NULL, ($container->services['debug.stopwatch'] ??= new \Symfony\Component\Stopwatch\Stopwatch(true)), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
