<?php

namespace ContainerXqwT76M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResolveContentLinksProcessorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Stenope\Bundle\Processor\ResolveContentLinksProcessor' shared service.
     *
     * @return \Stenope\Bundle\Processor\ResolveContentLinksProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/stenope/stenope/src/Behaviour/ProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/stenope/stenope/src/Behaviour/ContentManagerAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/stenope/stenope/src/Behaviour/ContentManagerAwareTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/stenope/stenope/src/Processor/ResolveContentLinksProcessor.php';
        include_once \dirname(__DIR__, 4).'/vendor/stenope/stenope/src/Routing/ContentUrlResolver.php';
        include_once \dirname(__DIR__, 4).'/vendor/stenope/stenope/src/Behaviour/HtmlCrawlerManagerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/stenope/stenope/src/Service/NaiveHtmlCrawlerManager.php';

        return $container->privates['Stenope\\Bundle\\Processor\\ResolveContentLinksProcessor'] = new \Stenope\Bundle\Processor\ResolveContentLinksProcessor(new \Stenope\Bundle\Routing\ContentUrlResolver(($container->services['router'] ?? self::getRouterService($container)), []), ($container->privates['Stenope\\Bundle\\Service\\NaiveHtmlCrawlerManager'] ??= new \Stenope\Bundle\Service\NaiveHtmlCrawlerManager()), 'content');
    }
}
