<?php

namespace ContainerXqwT76M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTermService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.0XuEpc8.App\Entity\Term' shared service.
     *
     * @return \App\Entity\Term
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.0XuEpc8": it needs an instance of "App\\Entity\\Term" but this type has been excluded in "config/services.yaml".');
    }
}
