<?php

namespace ContainerXqwT76M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTablerIconService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Survos\BootstrapBundle\Twig\Components\TablerIcon' autowired service.
     *
     * @return \Survos\BootstrapBundle\Twig\Components\TablerIcon
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/survos/bootstrap-bundle/src/Twig/Components/TablerIcon.php';

        $container->factories['service_container']['Survos\\BootstrapBundle\\Twig\\Components\\TablerIcon'] = function ($container) {
            return new \Survos\BootstrapBundle\Twig\Components\TablerIcon();
        };

        return $container->factories['service_container']['Survos\\BootstrapBundle\\Twig\\Components\\TablerIcon']($container);
    }
}
