<?php

namespace ContainerXqwT76M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserCreateCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.Survos\AuthBundle\Command\UserCreateCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.Survos\\AuthBundle\\Command\\UserCreateCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('survos:user:create', [], 'create a new user with a password', false, #[\Closure(name: 'Survos\\AuthBundle\\Command\\UserCreateCommand')] fn (): \Survos\AuthBundle\Command\UserCreateCommand => ($container->privates['Survos\\AuthBundle\\Command\\UserCreateCommand'] ?? $container->load('getUserCreateCommandService')));
    }
}
