<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9JdZFxX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9JdZFxX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9JdZFxX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9JdZFxX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9JdZFxX\App_KernelDevDebugContainer([
    'container.build_hash' => '9JdZFxX',
    'container.build_id' => '01cfddaa',
    'container.build_time' => 1698586270,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container9JdZFxX');
