<?php

namespace PhenxBundle\Repository;

use AppBundle\Repository\PosseEntityRepository;

/**
 * DomainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DomainRepository extends PosseEntityRepository
{

}
