<?php

namespace PhenxBundle\Repository;

use AppBundle\Repository\PosseEntityRepository;

/**
 * PhenxProtocolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhenxProtocolRepository extends PosseEntityRepository
{

}
