<?php

namespace PhenxBundle\Repository;

use AppBundle\Repository\PosseEntityRepository;

/**
 * VariableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VariableRepository extends PosseEntityRepository
{
}
