<?php

namespace ContainerKoSCo4l;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_FbzPOIService extends Survos_PixieBundle_Tests_Fixtures_TestKernelTestDebugContainer
{
    /**
     * Gets the private '.errored._FbzPOI' shared service.
     *
     * @return \Symfony\UX\Chartjs\Builder\ChartBuilderInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "Survos\\PixieBundle\\Controller\\PixieController::home()": the $chartBuilder argument is type-hinted with the non-existent class or interface: "Symfony\\UX\\Chartjs\\Builder\\ChartBuilderInterface".');
    }
}
