<?php

namespace ContainerKoSCo4l;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RfCO11cService extends Survos_PixieBundle_Tests_Fixtures_TestKernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.rfCO11c' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rfCO11c'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'chartBuilder' => ['privates', '.errored._FbzPOI', NULL, 'Cannot determine controller argument for "Survos\\PixieBundle\\Controller\\PixieController::home()": the $chartBuilder argument is type-hinted with the non-existent class or interface: "Symfony\\UX\\Chartjs\\Builder\\ChartBuilderInterface".'],
        ], [
            'chartBuilder' => '?',
        ]);
    }
}
