<?php

namespace ContainerKoSCo4l;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCsvHeaderEventListenerService extends Survos_PixieBundle_Tests_Fixtures_TestKernelTestDebugContainer
{
    /**
     * Gets the private 'Survos\PixieBundle\EventListener\CsvHeaderEventListener' shared autowired service.
     *
     * @return \Survos\PixieBundle\EventListener\CsvHeaderEventListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/src/EventListener/CsvHeaderEventListener.php';

        return $container->privates['Survos\\PixieBundle\\EventListener\\CsvHeaderEventListener'] = new \Survos\PixieBundle\EventListener\CsvHeaderEventListener();
    }
}
