<?php

namespace ContainerKoSCo4l;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSqliteServiceService extends Survos_PixieBundle_Tests_Fixtures_TestKernelTestDebugContainer
{
    /**
     * Gets the public 'Survos\PixieBundle\Service\SqliteService' shared autowired service.
     *
     * @return \Survos\PixieBundle\Service\SqliteService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/src/Service/SqliteService.php';

        return $container->services['Survos\\PixieBundle\\Service\\SqliteService'] = new \Survos\PixieBundle\Service\SqliteService();
    }
}
